import { describe, expect, it, vi } from "vitest";
import {
  buildYoutubeCaptionTrackUrls,
  formatYoutubeCaptionLines,
  parseYoutubeCaptionPayload,
  rankYoutubeCaptionTracks,
  resolveYoutubeCaptionTrack,
} from "../packages/core/src/content/youtube-captions.js";

describe("YouTube caption policy", () => {
  const tracks = [
    {
      baseUrl: "https://example.com/german-manual",
      languageCode: "de",
      name: { simpleText: "Deutsch" },
    },
    {
      baseUrl: "https://example.com/english-auto",
      languageCode: "en",
      kind: "asr",
      name: { simpleText: "English (auto-generated)" },
    },
  ];

  it("supports explicit manual-first and English-first ranking", () => {
    expect(
      rankYoutubeCaptionTracks({ captionTracks: tracks, priority: "manual-first" })[0]?.baseUrl,
    ).toContain("german-manual");
    expect(
      rankYoutubeCaptionTracks({ captionTracks: tracks, priority: "english-first" })[0]?.baseUrl,
    ).toContain("english-auto");
  });

  it("filters ASR and automatic-caption groups in manual-only mode", () => {
    expect(
      rankYoutubeCaptionTracks({
        captionTracks: tracks,
        automaticCaptionTracks: [
          { baseUrl: "https://example.com/automatic-group", languageCode: "fr" },
        ],
        skipAutoGenerated: true,
      }).map((track) => track.baseUrl),
    ).toEqual(["https://example.com/german-manual"]);
  });
});

describe("YouTube caption codec", () => {
  it("parses JSON3 timing and normalizes caption text", () => {
    const transcript = parseYoutubeCaptionPayload(
      JSON.stringify({
        events: [
          {
            tStartMs: 1_000,
            dDurationMs: 2_500,
            segs: [{ utf8: "Hello" }, { utf8: "  &amp; world" }],
          },
        ],
      }),
    );

    expect(transcript).toMatchObject({
      text: "Hello & world",
      segments: [{ startMs: 1_000, endMs: 3_500, text: "Hello & world" }],
    });
    expect(formatYoutubeCaptionLines(transcript?.lines ?? [])).toBe("[0:01] Hello & world");
  });

  it("parses XML and VTT through the same line model", () => {
    expect(
      parseYoutubeCaptionPayload(
        '<transcript><text start="1.5" dur="2">XML &amp; text</text></transcript>',
      ),
    ).toMatchObject({
      text: "XML & text",
      segments: [{ startMs: 1_500, endMs: 3_500, text: "XML & text" }],
    });
    expect(
      parseYoutubeCaptionPayload("WEBVTT\n\n00:00:02.000 --> 00:00:04.000\nVTT caption\n"),
    ).toMatchObject({
      text: "VTT caption",
      segments: [{ startMs: 2_000, endMs: 4_000, text: "VTT caption" }],
    });
  });

  it("ignores WebVTT header metadata, cue identifiers, and metadata blocks", () => {
    const transcript = parseYoutubeCaptionPayload(
      [
        "WEBVTT - YouTube captions",
        "Kind: captions",
        "Language: en",
        "",
        "NOTE generated metadata",
        "00:00:00.000 --> 00:00:01.000",
        "This comment is not a cue.",
        "",
        "STYLE",
        "::cue { color: lime; }",
        "",
        "REGION",
        "id:sidebar",
        "width:40%",
        "",
        "cue-17",
        "00:00:02.000 --> 00:00:04.000 align:start position:0%",
        "Actual caption",
        "second line",
      ].join("\n"),
    );

    expect(transcript).toMatchObject({
      text: "Actual caption second line",
      segments: [
        {
          startMs: 2_000,
          endMs: 4_000,
          text: "Actual caption second line",
        },
      ],
    });
  });

  it("tries canonical JSON3, base, and VTT variants until one parses", async () => {
    const loadText = vi.fn(async (url: string) =>
      url.includes("fmt=vtt")
        ? "WEBVTT\n\n00:00:03.000 --> 00:00:04.000\nFallback caption"
        : "not captions",
    );

    await expect(
      resolveYoutubeCaptionTrack("https://example.com/captions?lang=en&fmt=srv3", loadText),
    ).resolves.toMatchObject({ text: "Fallback caption" });
    expect(loadText.mock.calls.map(([url]) => url)).toEqual(
      buildYoutubeCaptionTrackUrls("https://example.com/captions?lang=en&fmt=srv3"),
    );
  });
});
